# Generated by Django 5.1.4 on 2026-04-02 04:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
                ('mobile', models.CharField(blank=True, help_text='Indian mobile number e.g. 98765 43210', max_length=15, null=True)),
                ('city', models.CharField(blank=True, default='Mysore', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Karnataka', max_length=100, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Karnataka Medical Council Reg. No.', max_length=50, null=True)),
                ('next_available_appointment_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New Appointment', 'New Appointment'), ('Appointment Cancelled', 'Appointment Cancelled')], max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notification',
            },
        ),
    ]
